language: php

php:
  - 5.6

before_script:
  - cp .env.travis .env
  - touch database/database.testing.sqlite
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate
  - php artisan db:seed

script:
- vendor/bin/phpunit